Repository digitalservicebund/a2j-rechtsantragstelle, pull requests merged in 2024-11, with the labels that each got.

#1367 ZOV: Create logic to retrieve court
  app/components/resultPage/DefaultResultPage.tsx
  app/components/resultPage/FluggastrechteResultPage.tsx
  app/domains/fluggastrechte/formular/context.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/services/__test__/getCourtByStartAndEndAirport.test.ts
  app/domains/fluggastrechte/services/getCourtByStartAndEndAirport.ts
  app/domains/fluggastrechte/vorabcheck/context.ts
  app/routes/beratungshilfe.vorabcheck.ergebnis.$.tsx
  app/routes/fluggastrechte.vorabcheck.ergebnis.$.tsx
  app/routes/geld-einklagen.vorabcheck.ergebnis.$.tsx
  app/routes/shared/components/ResultPage.tsx
  app/routes/shared/result.server.ts
  app/services/airports/hasPartnerCourt.ts
  app/services/airports/type.ts
  app/services/pdf/fluggastrechte/sections/firstPage/__test__/createLocalCourtAndDate.test.ts
  app/services/pdf/fluggastrechte/sections/firstPage/createLocalCourtAndDate.ts
  data/airports/data.json
  scripts/airports.ts
  tests/factories/fluggastrechte/userDataMock.ts
Labels: enhancement, ZOV

#1368 Add zeugen page
  app/domains/fluggastrechte/formular/__test__/stringReplacements.test.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/__test__/testcases.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/context.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/doneFunctions.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/flow.json
  app/domains/fluggastrechte/formular/stringReplacements.ts
  app/domains/fluggastrechte/formular/zusammenfassung/flow.json
  app/services/pdf/fluggastrechte/sections/firstPage/claimData/__test__/addPlaintiffDetails.test.ts
  app/services/pdf/fluggastrechte/sections/firstPage/claimData/addPlaintiffDetails.ts
  app/services/pdf/fluggastrechte/sections/reason/factsOfCases/__test__/addCompensationAmount.test.ts
  app/services/pdf/fluggastrechte/sections/reason/factsOfCases/addCompensationAmount.ts
  tests/e2e/flowPages/fluggastrechte/formular/startFluggastrechteFormular.ts
Labels: ZOV

#1369 feat(pkh-pdf-service): move versicherungen from section F_abzuege to I_zahlungeverpflichtungen
  app/services/pdf/beratungshilfe/sections/F_besitz/fillVermoegenswerte.ts
  app/services/pdf/prozesskostenhilfe/F_abzuege.ts
  app/services/pdf/prozesskostenhilfe/I_zahlungsverpflichtungen.ts
  app/services/pdf/prozesskostenhilfe/__test__/F_abzuege.test.ts
  app/services/pdf/prozesskostenhilfe/__test__/I_zahlungsverpflichtungen.test.ts
  app/services/pdf/shared/eigentumHelpers.ts
Labels: RAST

#1376 feat/add-new-possible-color-to-result-page: add color blue as default
  app/routes/shared/components/ResultPage.tsx
  app/services/cms/models/StrapiResultPageType.ts
Labels: ZOV

#1355 refactor(flows): replace cmsSlug with flowType
  app/domains/beratungshilfe/formular/index.ts
  app/domains/beratungshilfe/vorabcheck/index.ts
  app/domains/flows.server.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/vorabcheck/index.ts
  app/domains/geldEinklagen/formular/index.ts
  app/domains/geldEinklagen/vorabcheck/index.ts
  app/domains/prozesskostenhilfe/formular/index.ts
  app/services/cms/apiFromFlowType.ts
  app/services/cms/fetchAllFormFields.ts
  app/services/flow/__test__/flowTransitionValidation.test.ts
  app/services/flow/server/progress.ts
  app/services/session.server/__test__/getMigrationData.test.ts
Labels: ZOV, RAST

#1354 feat(CSPHeaders): strengthen headers
  .env.example
  app/entry.server.tsx
  app/services/env/env.server.ts
  app/services/env/web.ts
  app/services/security/__test__/cspHeader.test.ts
  app/services/security/cspHeader.server.tsx
  app/util/__test__/originFromUrlString.test.ts
  app/util/originFromUrlString.ts
Labels: ZOV, RAST

#1398 a11y(Skip to Content link)
  app/components/PageHeader.tsx
  app/components/navigation/SkipToContentLink.tsx
  app/root.tsx
  app/routes/shared/components/FormFlowPage.tsx
  app/util/shouldSetCacheControlHeader.ts
  app/util/url.ts
  eslint.config.js
  stories/SkipToContentLink.stories.tsx
  tests/e2e/util/expectPageToBeAccessible.ts
Labels: ZOV, RAST

#1408 Fix (aria labels): improvement to get convinced aria labels in pageheader
  app/components/Breadcrumbs.tsx
  app/components/PageHeader.tsx
  app/components/__test__/Breadcrumbs.test.tsx
  app/components/__test__/PageHeader.test.tsx
  app/root.tsx
  stories/PageHeader.stories.tsx
Labels: ZOV, RAST

#1404 feat(fgr): update pdf table with user data
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/createFactsOfCases.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/createFactsOfCases.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/addTableInfo.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/calculateDuration.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/addTable.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/addTableInfo.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/calculateDuration.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawTableColumnsValues.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawTableRowHead.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts
  app/domains/fluggastrechte/vorabcheck/context.ts
Labels: ZOV

#1395 feat/add-responsible-court-to-result-page: add new result page and co…
  app/domains/fluggastrechte/formular/__test__/stringReplacements.test.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/formular/stringReplacements.ts
  app/domains/fluggastrechte/services/__test__/getCourtByStartAndEndAirport.test.ts
  app/domains/fluggastrechte/services/getCourtByStartAndEndAirport.ts
  app/domains/fluggastrechte/vorabcheck/__test__/guards.test.ts
  app/domains/fluggastrechte/vorabcheck/__test__/stringReplacaments.test.ts
  app/domains/fluggastrechte/vorabcheck/flow.json
  app/domains/fluggastrechte/vorabcheck/guards.ts
  app/domains/fluggastrechte/vorabcheck/index.ts
  app/domains/fluggastrechte/vorabcheck/services/isErfolgAnalog.ts
  app/domains/fluggastrechte/vorabcheck/services/isFluggesellschaftInEU.ts
  app/domains/fluggastrechte/vorabcheck/stringReplacements.ts
  app/routes/shared/components/ResultPage.tsx
Labels: ZOV

#1409 Move to pdfkit preparation
  app/domains/beratungshilfe/services/pdf/index.ts
  app/domains/fluggastrechte/services/pdf/fluggastrechtePdfFromUserdata.ts
  app/domains/fluggastrechte/services/pdf/sections/__test__/createBankInformation.test.ts
  app/domains/fluggastrechte/services/pdf/sections/createBankInformation.ts
  app/domains/fluggastrechte/services/pdf/sections/createPageNumber.ts
  app/domains/fluggastrechte/services/pdf/sections/createStamp.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/__test__/createStatementClaim.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/__test__/addPlaintiffDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addAirlineDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addPlaintiffDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addPlannedFlightDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/createClaimData.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/createLocalCourtAndDate.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/createStatementClaim.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/addNewPageInCaseMissingVerticalSpace.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/createReasonPage.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/addCompensationAmount.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/addDetailedReason.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addCompensationAmount.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addDetailedReason.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addFlightDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addReason.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/createFactsOfCases.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/addTableInfo.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/addTableInfo.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawCell.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/tableConfigurations.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/legalAssessment/createLegalAssessment.ts
  app/domains/prozesskostenhilfe/services/pdf/index.ts
  app/routes/shared/pdfDownloadLoader.ts
  app/services/pdf/__test__/createPdfKitDocument.test.ts
  app/services/pdf/appendAttachment.ts
  app/services/pdf/appendPagesToPdf.ts
  app/services/pdf/createPdfKitDocument.ts
  app/services/pdf/pdfFromUserData.ts
Labels: ZOV, RAST

#1433 ZOV: add non-editable part of overview page
  app/domains/fluggastrechte/formular/__test__/stringReplacements.test.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/formular/services/__test__/getTotalClaimingPeople.test.ts
  app/domains/fluggastrechte/formular/services/getTotalClaimingPeople.ts
  app/domains/fluggastrechte/formular/services/getTotalCompensationClaim.ts
  app/domains/fluggastrechte/formular/stringReplacements.ts
Labels: ZOV

#1442 Add unit tests in the scope of move to pdfkit package
  app/domains/beratungshilfe/services/pdf/checklist/__test__/createChecklistPage.test.ts
  app/domains/beratungshilfe/services/pdf/checklist/__test__/createChecklistSteps.test.ts
  app/domains/beratungshilfe/services/pdf/checklist/createChecklistSteps.ts
  app/services/pdf/__test__/appendPagesToPdf.test.ts
  app/services/pdf/__test__/createHeading.test.ts
  app/services/pdf/attachment/__test__/createAttachmentEntries.test.ts
  app/services/pdf/attachment/__test__/createAttachmentPages.test.ts
  app/services/pdf/attachment/createAttachmentEntries.ts
  app/services/pdf/footer/__test__/createFooter.test.ts
  app/services/pdf/header/__test__/createHeader.test.ts
  tests/factories/mockPdfKit.ts
Labels: RAST

#1447 Pdf fluggastechte multi persons
  app/domains/fluggastrechte/services/pdf/sections/__test__/getFullPlaintiffName.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/__test__/createStatementClaim.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/__test__/addPlannedFlightDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addPlaintiffDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addPlannedFlightDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/createStatementClaim.ts
  app/domains/fluggastrechte/services/pdf/sections/getFullPlaintiffName.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/addNewPageInCaseMissingVerticalSpace.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/addCompensationAmount.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/addDetailedReason.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/addMultiplePersonsInfo.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/__test__/addReason.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addCompensationAmount.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addDetailedReason.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addMultiplePersonsInfo.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/addReason.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/createFactsOfCases.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/legalAssessment/__test__/createLegalAssessment.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/legalAssessment/createLegalAssessment.ts
  tests/factories/mockPdfKit.ts
Labels: ZOV

#1448 feat(pdf-service): add metadata to BerH and PKH pdfs
  app/domains/beratungshilfe/services/pdf/index.ts
  app/domains/prozesskostenhilfe/services/pdf/index.ts
  app/services/pdf/__test__/addMetadataToPdf.test.ts
  app/services/pdf/addMetadataToPdf.ts
Labels: RAST

#1436 refactor(stepId): leading slash in app
  app/domains/__test__/flowIds.test.ts
  app/domains/beratungshilfe/formular/__test__/testcases.ts
  app/domains/beratungshilfe/formular/anwaltlicheVertretung/__test__/testcases.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesAusgaben.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesEigentum.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesEigentumZusammenfassung.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesEinkommen.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesKinder.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesPartner.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesUnterhaltszahlungen.ts
  app/domains/beratungshilfe/formular/finanzielleAngaben/__test__/testcasesWohnung.ts
  app/domains/beratungshilfe/formular/rechtsproblem/__test__/testcases.ts
  app/domains/beratungshilfe/vorabcheck/__test__/testcases.ts
  app/domains/flowIds.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesAnnullierung.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesNichtBefoerderung.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testscasesVerspaetet.ts
  app/domains/fluggastrechte/formular/grundvoraussetzungen/__test__/testcases.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/__test__/testcases.ts
  app/domains/fluggastrechte/formular/prozessfuehrung/__test__/testcases.ts
  app/domains/fluggastrechte/formular/streitwertKosten/__test__/testscases.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesAnnullierungAbbruch.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesErfolg.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesErfolgAnalog.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesErfolgEU.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesNichtBefoerderungAbbruch.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesOtherErfolgs.ts
  app/domains/fluggastrechte/vorabcheck/__test__/testcasesVerspaetetAbbruch.ts
  app/domains/geldEinklagen/vorabcheck/__test__/testcases.ts
  app/domains/prozesskostenhilfe/formular/__test__/testcases.ts
  app/domains/prozesskostenhilfe/formular/antragstellendePerson/__test__/testcases.ts
  app/domains/prozesskostenhilfe/formular/finanzielleAngaben/__test__/testcasesWohnung.ts
  app/domains/prozesskostenhilfe/formular/persoenlicheDaten/__test__/testcases.ts
  app/domains/prozesskostenhilfe/formular/rechtsschutzversicherung/__test__/testcases.ts
  app/routes/beratungshilfe.zustaendiges-gericht.suche.tsx
  app/services/cms/index.server.ts
  app/services/flow/__test__/buildFlowController.test.ts
  app/services/flow/__test__/pruner.test.ts
  app/services/flow/__test__/stepIdConverter.test.ts
  app/services/flow/__test__/validFormPaths.test.ts
  app/services/flow/pruner.ts
  app/services/flow/server/buildFlowController.ts
  app/services/flow/server/lastStep.ts
  app/services/flow/server/progress.ts
  app/services/flow/stepIdConverter.ts
Labels: ZOV, RAST

#1459 feat: override to patched version cross-spawn
  package.json
Labels: ZOV, RAST

#1473 Simplify Docker image patch
  Dockerfile
Labels: ZOV, RAST

#1471 ZOV: Change string output for duration table
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/calculateDuration.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/drawTableColumnsHead.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/drawTableRowHead.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/calculateDuration.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawCell.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawTableColumnHead.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawTableRowHead.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts
Labels: ZOV

#1475 Feat overview page
  app/domains/fluggastrechte/components/ActualArrivalCards.tsx
  app/domains/fluggastrechte/components/StopOverCards.tsx
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
  app/domains/fluggastrechte/components/SummaryDataOverviewCard.tsx
  app/domains/fluggastrechte/services/airports/getAirportByIataCode.ts
  app/domains/fluggastrechte/services/summaryPage/getOverviewData.ts
  app/domains/fluggastrechte/services/summaryPage/getStringWithSpaceIfStringExists.ts
  app/domains/fluggastrechte/services/summaryPage/stoppOver.ts
  app/routes/shared/components/FormFlowPage.tsx
  app/routes/shared/formular.server.ts
Labels: ZOV

#1474 chore(Dockerfile): explicit npm upgrade & docs
  Dockerfile
Labels: ZOV, RAST

#1498 Disable add button array summary
  .github/workflows/ci-pipeline.yml
  README.md
  app/components/arraySummary/ArraySummary.tsx
  app/components/arraySummary/ArraySummaryDataItems.tsx
  app/components/arraySummary/__test__/ArraySummary.test.tsx
  app/components/arraySummary/__test__/ArraySummaryDataItems.test.tsx
  app/domains/beratungshilfe/formular/finanzielleAngaben/arrayConfiguration.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/formular/services/__test__/isTotalClaimWillSucceddedAboveLimit.test.ts
  app/domains/fluggastrechte/formular/services/isTotalClaimAboveLimit.ts
  app/domains/prozesskostenhilfe/formular/finanzielleAngaben/arrayConfiguration.ts
  app/domains/shared/formular/finanzielleAngaben/arrayConfiguration.ts
  app/services/array/__test__/getArraySummaryData.test.ts
  app/services/array/getArraySummaryData.ts
  app/services/array/index.ts
  app/services/flow/server/buildFlowController.ts
  app/services/flow/validFormPaths.ts
  package.json
Labels: ZOV
