Repository digitalservicebund/a2j-rechtsantragstelle, pull requests merged in 2024-12, with the labels that each got.

#1510 Ander ersatzverbindung beschreibung optional
  app/domains/fluggastrechte/formular/flugdaten/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesAnnullierung.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesNichtBefoerderung.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testscasesVerspaetet.ts
  app/domains/fluggastrechte/formular/flugdaten/context.ts
  app/domains/fluggastrechte/formular/flugdaten/doneFunctions.ts
Labels: ZOV

#1507 feat/change-sentences-in-claim-pdf: change two sentences in pdf
  app/domains/fluggastrechte/services/pdf/configurations.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/__test__/createStatementClaim.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/__test__/addDefendantPartyList.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/claimData/addDefendantPartyList.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/createStatementClaim.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/compensationAmount/addMultiplePersonsInfo.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/detailedReason/__test__/addDetailedReason.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/detailedReason/addDetailedReason.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/detailedReason/addMultiplePersonsText.ts
Labels: ZOV

#1526 change-link-and-text-in-zov-summary-page for witnesses
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
  app/domains/fluggastrechte/services/summaryPage/getOverviewData.ts
Labels: ZOV

#1519 feat(pdf-service): print name in signature form field of pkh pdf...
  app/domains/prozesskostenhilfe/services/pdf/__test__/printNameInSignatureFormField.test.ts
  app/domains/prozesskostenhilfe/services/pdf/index.ts
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/K_footer.ts
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/__test__/K_footer.test.ts
  app/domains/prozesskostenhilfe/services/pdf/printNameInSignatureFormField.ts
  app/services/pdf/fillPdf.server.ts
Labels: RAST

#1518 feat(pdf-service): append hinweisblatt to pkh pdf
  app/domains/beratungshilfe/services/pdf/index.ts
  app/domains/prozesskostenhilfe/services/pdf/__test__/loadHinweisblatt.test.ts
  app/domains/prozesskostenhilfe/services/pdf/__test__/prozesskostenhilfePdfFromUserdata.test.ts
  app/domains/prozesskostenhilfe/services/pdf/index.ts
  app/domains/prozesskostenhilfe/services/pdf/loadHinweisblatt.ts
  data/pdf/prozesskostenhilfe/Formular_Hinweisblatt_Prozess_Verfahrenskostenhilfe.pdf
Labels: RAST

#1530 fix(pdf-service): styling fixes after move to pdfkit
  app/domains/beratungshilfe/services/pdf/checklist/__test__/createChecklistPage.test.ts
  app/domains/beratungshilfe/services/pdf/checklist/__test__/createChecklistSteps.test.ts
  app/domains/beratungshilfe/services/pdf/checklist/createChecklistPage.ts
  app/domains/beratungshilfe/services/pdf/checklist/createChecklistSteps.ts
  app/services/pdf/attachment/createAttachmentEntries.ts
  app/services/pdf/pdfStyles.ts
Labels: RAST

#1539 More pdf table fix
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/compensationAmount/addCompensationAmount.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/calculateDuration.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/addTableInfo.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/calculateDuration.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/legalAssessment/createLegalAssessment.ts
Labels: ZOV

#1538 display data for cedents instead of plaintiff
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
Labels: ZOV

#1534 feat(textarea): add maxlength via strapi defaulting to 5000
  app/components/inputs/Textarea.tsx
  app/components/inputs/__test__/Textarea.test.tsx
  app/services/cms/components/StrapiTextarea.tsx
Labels: ZOV, RAST

#1549 add aria-required attribute to input
  app/components/inputs/Input.tsx
  app/components/inputs/__test__/Input.test.tsx
Labels: ZOV, RAST

#1508 test(flows): add coverage
  app/domains/__test__/flows.test.ts
  app/domains/prozesskostenhilfe/formular/rechtsschutzversicherung/__test__/testcases.ts
Labels: ZOV, RAST

#1551 Feat/add aria required for screen readers
  app/components/inputs/Select.tsx
  app/components/inputs/Textarea.tsx
  app/components/inputs/__test__/Select.test.tsx
  app/components/inputs/__test__/Textarea.test.tsx
Labels: ZOV, RAST
