Repository digitalservicebund/a2j-rechtsantragstelle, pull requests merged in 2025-03, with the labels that each got.

#1796 ZOV: add string replacement for responsibleAirportForCourt
  app/domains/fluggastrechte/formular/__test__/stringReplacements.test.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/fluggastrechte/formular/stringReplacements.ts
Labels: ZOV

#1821 Implement mobile-only SideNav: JS/no-JS
  app/components/Footer.tsx
  app/components/navigation/FlowNavigation.tsx
  app/components/navigation/NavigationList.tsx
  app/components/navigation/SideNavMobile.tsx
  app/components/navigation/__test__/FlowNavigation.test.tsx
  app/components/navigation/__test__/SideNavMobile.test.tsx
  app/routes/shared/components/FormFlowPage.tsx
  app/routes/shared/formular.server.ts
Labels: enhancement, RAST

#1820 ZOV: validate of duplication entry in stopover option page
  app/domains/fluggastrechte/formular/multiFieldsValidation.ts
  app/domains/fluggastrechte/formular/services/__test__/validation.test.ts
  app/domains/fluggastrechte/formular/services/validation.ts
Labels: ZOV

#1817 remove hardcoded SummaryPage
  app/domains/fluggastrechte/components/ActualArrivalCards.tsx
  app/domains/fluggastrechte/components/AirlineDetailsOverviewCard.tsx
  app/domains/fluggastrechte/components/StopOverCards.tsx
  app/domains/fluggastrechte/components/StreitbeilegungCard.tsx
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
  app/domains/fluggastrechte/components/SummaryDataOverviewCard.tsx
  app/domains/fluggastrechte/components/__test__/AirlineDetailsOverviewCard.test.tsx
  app/domains/fluggastrechte/components/__test__/userAirlineDetails.test.ts
  app/domains/fluggastrechte/components/useAirlineDetails.tsx
  app/domains/fluggastrechte/components/useDelayFlightAirports.tsx
  app/domains/fluggastrechte/components/useStepOverAirports.tsx
  app/domains/fluggastrechte/services/summaryPage/getOverviewData.ts
  app/domains/fluggastrechte/services/summaryPage/getStringWithSpaceIfStringExists.ts
  app/domains/fluggastrechte/services/summaryPage/stoppOver.ts
  app/routes/__test__/api.airline.test.ts
  app/routes/api.airline.$iataCode.ts
  app/routes/delay-flight-airports.ts
  app/routes/shared/components/FormFlowPage.tsx
  app/routes/step-over-airports.ts
Labels: ZOV

#1838 Create accordion component in list item
  app/components/Accordion.tsx
  app/components/AccordionItem.tsx
  app/components/ListItem.tsx
  app/components/__test__/Accordion.test.tsx
  app/components/__test__/AccordionItem.test.tsx
  app/root.tsx
  app/services/cms/models/StrapiAccordion.ts
  app/services/cms/models/StrapiListItem.ts
  app/services/translations/translationsContext.ts
  stories/Accordion.stories.tsx
  stories/FilesUpload.stories.tsx
Labels: enhancement, RAST

#1870 Create staging only summary page for beratungshilfe antrag
  app/domains/__test__/flows.test.ts
  app/domains/beratungshilfe/formular/__test__/testcases.ts
  app/domains/beratungshilfe/formular/xstateConfig.ts
  app/domains/beratungshilfe/formular/zusammenfassung/xstateConfig.ts
  app/services/featureFlags/index.ts
  tests/e2e/domains/beratungshilfe/formular/beratungshilfe.formular.spec.ts
Labels: enhancement, RAST

#1339 Doc(adr): move formFields from CMS into app
  doc/adr/0022-pageConfig-inside-application.md
Labels: ZOV, RAST

#1900 fix: adjust Sidenav menu width
  app/components/navigation/FlowNavigation.tsx
  app/routes/shared/components/FormFlowPage.tsx
Labels: bug, RAST

#1896 Kpf wegweiser new flow pages to basisinfo
  app/domains/__test__/TestCases.ts
  app/domains/__test__/flows.test.ts
  app/domains/kontopfaendung/__test__/testMachine.ts
  app/domains/kontopfaendung/__test__/testcases.ts
  app/domains/kontopfaendung/wegweiser/context.ts
  app/domains/kontopfaendung/wegweiser/xStateConfig.ts
Labels: enhancement, RAST

#1902 fix(PKH): display item with price and frequency and calculate by month
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/F_abzuege.ts
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/__test__/F_abzuege.test.ts
  app/routes/shared/__test__/pdfDownloadLoader.test.ts
Labels: bug, RAST

#1901 feat(airports): update data
  data/airports/data.json
  scripts/airports.ts
Labels: ZOV

#1887 Add validation on cancel page
  app/domains/fluggastrechte/formular/services/validation/__test__/validateCancelFlightReplacementPage.test.ts
  app/domains/fluggastrechte/formular/services/validation/validateCancelFlightReplacementPage.ts
Labels: ZOV
