Repository digitalservicebund/a2j-rechtsantragstelle, pull requests merged in 2025-04, with the labels that each got.

#1920 refactor: update styles.
  app/components/Accordion.tsx
  app/components/AccordionItem.tsx
Labels: enhancement, RAST

#1926 KPF Wegweiser: Add 1 new flow page to "Ermittlung des pfändungsfreien Betrags + Einmal-/Nachzahlungen"
  app/domains/kontopfaendung/__test__/stringReplacements.test.ts
  app/domains/kontopfaendung/__test__/testcases.ts
  app/domains/kontopfaendung/wegweiser/context.ts
  app/domains/kontopfaendung/wegweiser/stringReplacements.ts
  app/domains/kontopfaendung/wegweiser/xStateConfig.ts
Labels: enhancement, RAST

#1919 fix: special chars issue
  app/components/inputs/autoSuggestInput/customComponents/FormatOptionLabel.tsx
  app/components/inputs/autoSuggestInput/customComponents/__test__/FormatOptionLabel.test.tsx
Labels: ZOV

#1949 add string replacements for meta information
  app/routes/shared/formular.server.ts
  app/routes/shared/result.server.ts
  app/routes/shared/vorabcheck.server.ts
Labels: ZOV, RAST

#1945 Move to new version of validation form
  .storybook/RFCFormerProvider.tsx
  app/components/filesUpload/FilesUpload.tsx
  app/components/filesUpload/__test__/FilesUpload.test.tsx
  app/components/form/ValidatedFlowForm.tsx
  app/components/form/__test__/ValidatedFlowForm.test.tsx
  app/components/inputs/Checkbox.tsx
  app/components/inputs/HiddenInput.tsx
  app/components/inputs/Input.tsx
  app/components/inputs/Radio.tsx
  app/components/inputs/RadioGroup.tsx
  app/components/inputs/Select.tsx
  app/components/inputs/Textarea.tsx
  app/components/inputs/__test__/Checkbox.test.tsx
  app/components/inputs/__test__/HiddenInput.test.tsx
  app/components/inputs/__test__/Input.test.tsx
  app/components/inputs/__test__/Radio.test.tsx
  app/components/inputs/__test__/RadioGroup.test.tsx
  app/components/inputs/__test__/Select.test.tsx
  app/components/inputs/__test__/Textarea.test.tsx
  app/components/inputs/autoSuggestInput/AutoSuggestInput.tsx
  app/components/inputs/autoSuggestInput/__test__/AutoSuggestInput.test.tsx
  app/components/inputs/tile/TileGroup.tsx
  app/components/inputs/tile/TileRadio.tsx
  app/components/inputs/tile/__test__/TileGroup.test.tsx
  app/components/inputs/tile/__test__/TileRadio.test.tsx
  app/components/userFeedback/FeedbackFormBox.tsx
  app/domains/beratungshilfe/vorabcheck/__test__/pages.test.ts
  app/routes/action.send-feedback.ts
  app/routes/action.send-rating.ts
  app/routes/beratungshilfe.zustaendiges-gericht.suche.tsx
  app/routes/shared/formular.server.ts
  app/routes/shared/vorabcheck.server.ts
  app/services/session.server/__test__/fieldsFromContext.test.ts
  app/services/session.server/fieldsFromContext.ts
  app/services/upload/buildFileUploadError.ts
  app/services/upload/fileUploadHelpers.server.ts
  app/services/upload/validateUploadedFile.ts
  app/services/validation/stepValidator/buildStepValidator.ts
  app/services/validation/useStringField.ts
  package-lock.json
  package.json
  stories/AutoSuggestInput.stories.tsx
  stories/Checkbox.stories.tsx
  stories/DateInput.stories.tsx
  stories/FilesUpload.stories.tsx
  stories/Input.stories.tsx
  stories/RadioGroup.stories.tsx
  stories/Select.stories.tsx
  stories/Textarea.stories.tsx
  stories/Tiles.stories.tsx
  stories/TimeInput.stories.tsx
Labels: ZOV, RAST

#2016 add to sentry ignore errors: Detected manifest version mismatch, relo…
  app/entry.client.tsx
Labels: ZOV, RAST

#2023 add fonts for self hosting
  app/root.tsx
  app/styles.css
  public/fonts/Fira-Sans.woff2
Labels: ZOV, RAST
