Repository digitalservicebund/a2j-rechtsantragstelle, pull requests merged in 2025-01, with the labels that each got.

#1327 Unify pdf field filling incl auto-size
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/A_person.ts
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/__test__/A_person.test.ts
  app/services/pdf/__test__/fillPdfField.test.ts
  app/services/pdf/fileTypes.ts
  app/services/pdf/fillPdf.server.ts
  app/services/pdf/fillPdfField.ts
  app/services/pdf/pdf.generator.ts
  data/pdf/beratungshilfe/beratungshilfe.generated.ts
  data/pdf/prozesskostenhilfe/prozesskostenhilfe.generated.ts
Labels: RAST

#1582 lodash: use specific functions import from submodules
  app/domains/beratungshilfe/formular/xstateConfig.ts
  app/domains/fluggastrechte/formular/index.ts
  app/domains/geldEinklagen/formular/index.ts
  app/domains/prozesskostenhilfe/formular/finanzielleAngaben/einkuenfte/xStateConfig.ts
  app/domains/prozesskostenhilfe/formular/finanzielleAngaben/xstateConfig.ts
  app/domains/prozesskostenhilfe/services/pdf/pdfForm/I_zahlungsverpflichtungen.ts
  app/routes/shared/pdfDownloadLoader.ts
  app/services/array/resolveArraysFromKeys.ts
  app/services/cms/fetchAllFormFields.ts
  app/services/flow/pageData.ts
  app/services/flow/pruner.ts
  app/services/flow/server/buildFlowController.ts
  app/services/flow/server/flowTransitionValidation.ts
  app/services/session.server/fieldsFromContext.ts
  app/services/session.server/index.ts
  scripts/airlines.ts
  scripts/airports.ts
  scripts/unusedStrapiEntries.ts
Labels: ZOV, RAST

#1591 feat: same airports will show error(s)
  app/domains/fluggastrechte/vorabcheck/multiFieldsValidation.ts
  app/domains/fluggastrechte/vorabcheck/services/__test__/validation.test.ts
  app/domains/fluggastrechte/vorabcheck/services/validation.ts
  app/domains/multiFieldsFlowValidation.ts
Labels: ZOV

#1590 Add pdf table info annuellierung
  app/domains/fluggastrechte/services/pdf/sections/firstPage/__test__/createLocalCourtAndDate.test.ts
  app/domains/fluggastrechte/services/pdf/sections/firstPage/createLocalCourtAndDate.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawCell.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/drawTableColumnsValues.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts
  app/domains/fluggastrechte/vorabcheck/context.ts
Labels: ZOV

#1597 ZOV: add airlines address input
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesAnnullierung.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesNichtBefoerderung.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testscasesVerspaetet.ts
  app/domains/fluggastrechte/formular/flugdaten/context.ts
  app/domains/fluggastrechte/formular/flugdaten/flow.json
  app/domains/fluggastrechte/formular/streitwertKosten/__test__/testscases.ts
  app/domains/fluggastrechte/formular/streitwertKosten/flow.json
  tests/e2e/domains/fluggastrechte/formular/startFluggastrechteFormular.ts
Labels: ZOV

#1596 Add new flow for annulierung klage
  app/domains/fluggastrechte/formular/flugdaten/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/flugdaten/__test__/testcasesAnnullierung.ts
  app/domains/fluggastrechte/formular/flugdaten/context.ts
  app/domains/fluggastrechte/formular/flugdaten/doneFunctions.ts
  app/domains/fluggastrechte/formular/flugdaten/flow.json
  app/domains/fluggastrechte/formular/flugdaten/guards.ts
Labels: ZOV

#1631 refactor(getConnectionDetails): add annullierung dates info
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/__test__/getConnectionDetails.test.ts
  app/domains/fluggastrechte/services/pdf/sections/reason/factsOfCases/table/getConnectionDetails.ts
Labels: ZOV

#1627 ZOV: Add airlines address in overview page
  app/domains/fluggastrechte/components/AirlineDetailsOverviewCard.tsx
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
  app/domains/fluggastrechte/components/__test__/AirlineDetailsOverviewCard.test.tsx
  app/domains/fluggastrechte/components/__test__/userAirlineDetails.test.ts
  app/domains/fluggastrechte/components/useAirlineDetails.tsx
  app/domains/fluggastrechte/services/summaryPage/getOverviewData.ts
  app/routes/__test__/api.airline.test.ts
  app/routes/api.airline.$iataCode.ts
Labels: ZOV

#1635 feat(fgr): show right schlichtungsstelle
  app/domains/fluggastrechte/vorabcheck/__test__/stringReplacaments.test.ts
  app/domains/fluggastrechte/vorabcheck/index.ts
  app/domains/fluggastrechte/vorabcheck/stringReplacements.ts
  data/airlines/data.json
Labels: ZOV
