Repository digitalservicebund/a2j-rechtsantragstelle, pull requests merged in 2025-02, with the labels that each got.

#1722 add außergerichtliche Streitbeteiligung to summary page
  app/domains/fluggastrechte/components/StreitbeilegungCard.tsx
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
Labels: ZOV

#1732 refactor(getXXXProps): migrate StrapiCookieBannerSchema
  app/root.tsx
  app/services/cms/models/StrapiCookieBannerSchema.ts
Labels: RAST

#1748 feat: add new option "noSpecification" to streitbeilegung
  app/domains/fluggastrechte/formular/grundvoraussetzungen/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/grundvoraussetzungen/__test__/testcases.ts
  app/domains/fluggastrechte/formular/grundvoraussetzungen/context.ts
  app/domains/fluggastrechte/formular/grundvoraussetzungen/doneFunctions.ts
  app/domains/fluggastrechte/formular/grundvoraussetzungen/flow.json
  app/domains/fluggastrechte/formular/grundvoraussetzungen/guard.ts
Labels: ZOV

#1754 Build 1st step kontopfändung flow pages
  app/domains/schulden/vorabcheck/context.ts
  app/domains/schulden/vorabcheck/xstateConfig.ts
Labels: enhancement, RAST

#1756 Build kontopfändung basisinfo flow
  app/domains/schulden/vorabcheck/context.ts
  app/domains/schulden/vorabcheck/xstateConfig.ts
  app/services/validation/YesNoAnswer.tsx
Labels: enhancement, RAST

#1757 ZOV: move zeugen under prozessfuehrung
  app/domains/fluggastrechte/components/SummaryDataOverview.tsx
  app/domains/fluggastrechte/formular/persoenlicheDaten/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/__test__/testcases.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/context.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/doneFunctions.ts
  app/domains/fluggastrechte/formular/persoenlicheDaten/flow.json
  app/domains/fluggastrechte/formular/prozessfuehrung/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/prozessfuehrung/__test__/testcases.ts
  app/domains/fluggastrechte/formular/prozessfuehrung/context.ts
  app/domains/fluggastrechte/formular/prozessfuehrung/doneFunctions.ts
  app/domains/fluggastrechte/formular/prozessfuehrung/flow.json
  tests/e2e/domains/fluggastrechte/formular/startFluggastrechteFormular.ts
Labels: ZOV

#1713 feat: implement first draft summary overview page
  app/components/PageContent.tsx
  app/components/form/formFlowContext.tsx
  app/components/summaryOverview/SummaryOverviewBox.tsx
  app/components/summaryOverview/SummaryOverviewBoxArray.tsx
  app/components/summaryOverview/SummaryOverviewBoxItem.tsx
  app/components/summaryOverview/SummaryOverviewBoxWrapped.tsx
  app/components/summaryOverview/SummaryOverviewSection.tsx
  app/components/summaryOverview/__test__/SummaryOverviewBox.test.tsx
  app/components/summaryOverview/__test__/SummaryOverviewBoxArray.test.tsx
  app/components/summaryOverview/__test__/SummaryOverviewBoxItem.test.tsx
  app/components/summaryOverview/__test__/SummaryOverviewBoxWrapped.test.tsx
  app/components/summaryOverview/__test__/SummaryOverviewSection.test.tsx
  app/components/summaryOverview/__test__/addArrayIndexToPathUrl.test.ts
  app/components/summaryOverview/__test__/getArraySummaryObject.test.ts
  app/components/summaryOverview/__test__/getInlineItemValues.test.ts
  app/components/summaryOverview/__test__/getItemValueBox.test.ts
  app/components/summaryOverview/addArrayIndexToPathUrl.ts
  app/components/summaryOverview/getArraySummaryObject.ts
  app/components/summaryOverview/getInlineItemValues.ts
  app/components/summaryOverview/getItemValueBox.ts
  app/routes/shared/__test__/pdfDownloadLoader.test.ts
  app/routes/shared/components/FormFlowPage.tsx
  app/routes/shared/formular.server.ts
  app/routes/shared/pdfDownloadLoader.ts
  app/services/cms/models/StrapiContentComponent.ts
  app/services/cms/models/StrapiSummaryOverviewSection.ts
  app/services/cms/models/__test__/StrapiStringOptional.test.ts
  app/services/cms/models/__test__/StrapiSummaryOverview.test.ts
  app/services/flow/__test__/pruner.test.ts
  app/services/flow/formular/buildFormularServerTranslations.ts
  app/services/flow/pruner.ts
  app/services/session.server/__test__/getMigrationData.test.ts
  app/services/session.server/crossFlowMigration.ts
Labels: ZOV, RAST

#1759 Kontopfaendung build Zwischenseite and unterhalt
  app/domains/schulden/vorabcheck/context.ts
  app/domains/schulden/vorabcheck/xstateConfig.ts
  app/services/validation/YesNoAnswer.tsx
Labels: enhancement, RAST

#1776 Build pages and states: Kontopfaendung build ermittlung betrags
  app/domains/schulden/vorabcheck/__test__/context.test.ts
  app/domains/schulden/vorabcheck/__test__/index.test.ts
  app/domains/schulden/vorabcheck/__test__/xStateConfig.test.ts
  app/domains/schulden/vorabcheck/context.ts
  app/domains/schulden/vorabcheck/index.ts
  app/domains/schulden/vorabcheck/xStateConfig.ts
  app/domains/schulden/vorabcheck/xstateConfig.ts
  app/services/validation/YesNoAnswer.tsx
Labels: enhancement, RAST

#1775 add noSpecification to Videoverhandlung
  app/domains/fluggastrechte/formular/prozessfuehrung/__test__/doneFunctions.test.ts
  app/domains/fluggastrechte/formular/prozessfuehrung/context.ts
Labels: ZOV

#1780 feat: flatten state and update unit tests
  app/domains/schulden/vorabcheck/__test__/xStateConfig.test.ts
  app/domains/schulden/vorabcheck/xStateConfig.ts
Labels: enhancement, RAST

#1784 feat/responsiveness of header
  app/components/PageHeader.tsx
Labels: ZOV, RAST

#1785 Kontopfaendung updates
  app/domains/schulden/vorabcheck/__test__/context.test.ts
  app/domains/schulden/vorabcheck/__test__/index.test.ts
  app/domains/schulden/vorabcheck/__test__/xStateConfig.test.ts
  app/domains/schulden/vorabcheck/context.ts
  app/domains/schulden/vorabcheck/xStateConfig.ts
Labels: enhancement, RAST

#1800 Kontopfaendung restructure routes
  app/domains/__test__/flowIds.test.ts
  app/domains/contexts.ts
  app/domains/flowIds.ts
  app/domains/flows.server.ts
  app/domains/kontopfaendung/wegweiser/context.ts
  app/domains/kontopfaendung/wegweiser/index.ts
  app/domains/kontopfaendung/wegweiser/xStateConfig.ts
  app/domains/multiFieldsFlowValidation.ts
  app/routes/kontopfaendung._index.tsx
  app/routes/kontopfaendung.tsx
  app/routes/kontopfaendung.wegweiser.$.tsx
  app/services/flow/server/__test__/flowTransitionValidation.test.ts
Labels: enhancement, RAST
